annotations:
  created: "2025-09-16T11:54:57Z"
  revision: 5b2e94b1d2105c0103334bb4f18dcf642f3284ac
apiVersion: v2
appVersion: 3.1.1
description: Deploy MX Grid Manager UI pods on Kubernetes
name: orch-ui-root
type: application
version: 3.1.1
